apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-processor
  labels:
    app: rust-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rust-processor
  template:
    metadata:
      labels:
        app: rust-processor
    spec:
      containers:
        - name: rust-processor
          image: k-os/rust-processor:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
            limits:
              cpu: 500m
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rust-processor
spec:
  type: ClusterIP
  selector:
    app: rust-processor
  ports:
    - port: 80
      targetPort: 8081
